name: CI

on:
  workflow_dispatch:
    inputs:
      runner_os:
        description: 'Runner OS'
        default: 'ubuntu-latest'
        type: string

env:
  UPLOAD_ARTIFACT: true

jobs:
  build:
    permissions: write-all
    runs-on: ${{ inputs.runner_os }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Artifact
        if: env.UPLOAD_ARTIFACT == 'true'
        uses: actions/upload-artifact@v4
        with:
          path: .
